services:
  - name: woopos-web
    type: web
    env: python
    region: oregon
    buildCommand: |
        apt-get update && apt-get install -y wkhtmltopdf
        pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

 

  - name: celery-worker-campaign
    type: worker
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.celery_app worker -l info --pool=solo -Q scheduler,emails,campaigns
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-beat-campaign
    type: worker
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.celery_app beat -l info
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-worker-discount
    type: worker
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y libnss3 libatk1.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libasound2 fonts-liberation
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: celery -A routes.admin_function.discount_calculation worker --loglevel=info --pool=solo
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-beat-discount
    type: worker
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: celery -A routes.admin_function.discount_calculation beat --loglevel=info
    envVars:
      - key: REDIS_URL
        sync: false