services:
  # 🚀 FastAPI Web Service
  - name: woopos-web
    type: web
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString

  # 🛠️ Celery Worker for campaign_tasks
  - name: worker-campaign
    type: worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.campaign_tasks worker -l info --pool=solo
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString

  # ⏰ Celery Beat for campaign_tasks
  - name: beat-campaign
    type: worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.campaign_tasks beat -l info
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString

  # 🛠️ Celery Worker for discount_calculation
  - name: worker-discount
    type: worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.admin_function.discount_calculation worker --loglevel=info --pool=solo
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString

  # ⏰ Celery Beat for discount_calculation
  - name: beat-discount
    type: worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.admin_function.discount_calculation beat --loglevel=info
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: woopos-redis
          property: connectionString

databases:
  # 🧠 Redis Database for Celery Broker/Backend
  - name: woopos-redis
    type: redis
    plan: free
    region: oregon
