services:
  - name: woopos-web
    type: web
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

 

  - name: celery-worker-campaign
    type: worker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.campaign_tasks worker --loglevel=info --pool=solo
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-beat-campaign
    type: worker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.campaign.sending_campaign.services.campaign_tasks beat --loglevel=info
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-worker-discount
    type: worker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.admin_function.discount_calculation worker --loglevel=info --pool=solo
    envVars:
      - key: REDIS_URL
        sync: false

  - name: celery-beat-discount
    type: worker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A routes.admin_function.discount_calculation beat --loglevel=info
    envVars:
      - key: REDIS_URL
        sync: false